name: rewarded_interstitial_example
description: Example project for demoing rewarded interstitial ads.
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  supabase_flutter: ^2.9.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.5
  http: ^1.1.0
  webview_flutter: ^4.4.2
  connectivity_plus: ^6.0.5
  app_links: ^3.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
